### ISSUE TITLE
[BUG] Azure pipeline task not reporting failures to the pipeline

### ISSUE THREAD

**Issue by brunogoettmann** [microsoft/azure-load-testing#133]
**Describe the bug**
Azure DevOps task for Azure Load Testing is no longer reporting failures on the test nor there doesn't seem to have a similar configuration option to fail the task when the test fails.

**To Reproduce**
1. Install v1.2.18 of Azure Load Testing from [here](https://marketplace.visualstudio.com/items?itemName=AzloadTest.AzloadTesting&ssr=false#overview)
2. Create a jMeter test case that reports error
3. Create a pipeline with a `AzureLoadTest@1` task
4. Set `percentage(error) > 0` as failure criteria
5. Run the pipeline

```yaml
version: v0.1
testId: my-test
description: My test description
engineInstances: 1
testPlan: test-example.jmx
failureCriteria:
- percentage(error) > 0
```

**Expected behavior**
The pipeline task fails if the there's any test failures

**Additional context**
It seems to be a regression from v1.2.17 to v1.2.18.

AB#1719418
